/**
 * Generates today's digest into the docs archive (docs/digests/<date>.md) and
 * refreshes the archive index. Run by the scheduled digest workflow (and
 * locally via `pnpm --filter @prompt2md/web digest:archive`). Requires built
 * workspace packages; Node >= 22.6 (type stripping).
 */
import { mkdir, readdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { generateDigest } from "../lib/digest.ts";

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "..", "..", "..");
const archiveDir = join(repoRoot, "docs", "digests");

const digest = await generateDigest({});
await mkdir(archiveDir, { recursive: true });

const page = [
  digest.markdown,
  "",
  `> Raw source payloads: ${digest.rawTokens.toLocaleString()} tokens → this digest: ${digest.digestTokens.toLocaleString()} tokens (${Math.round(digest.ratio * 100)}% of raw). Generated ${digest.generatedAt} by the prompt2md pipeline.`,
  "",
].join("\n");
await writeFile(join(archiveDir, `${digest.date}.md`), page, "utf8");

const entries = (await readdir(archiveDir))
  .filter((f) => /^\d{4}-\d{2}-\d{2}\.md$/.test(f))
  .sort()
  .reverse();
const index = [
  "# Daily Digest archive",
  "",
  "Each entry is generated by the prompt2md pipeline from vetted public APIs —",
  "see [source map & vetting checklist](../DIGEST-SOURCES).",
  "",
  ...entries.map((f) => `- [${f.replace(".md", "")}](./${f.replace(".md", "")})`),
  "",
].join("\n");
await writeFile(join(archiveDir, "index.md"), index, "utf8");

console.log(`archived digest ${digest.date}: ${digest.rawTokens} -> ${digest.digestTokens} tokens (${entries.length} entries in archive)`);
